name: Build and Publish to GitHub Packages

on:
  push:
    branches:
      - main  # Déclenche l'action lors d'un push sur la branche principale
  release:
    types: [created]  # Déclenche l'action lors d'une création de release

permissions:
  contents: read
  packages: write  # Nécessaire pour publier sur GitHub Packages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Vous pouvez changer par 'adopt' ou 'zulu' si nécessaire
          java-version: '8'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build the project
        run: ./gradlew build

      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
